require 'rake/extensiontask'
require "rake/testtask"

lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

spec = Gem::Specification.new do |s|

  s.name          = "constraint"
  s.version       = "1.0.0"
  s.authors       = ["TODO"]
  s.email         = ["TODO"]

  s.summary       = "TODO"
  s.description   = "TODO"
  s.homepage      = "TODO"
  s.license       = "MIT"

  s.platform = Gem::Platform::RUBY
  s.extensions = FileList["ext/**/extconf.rb"]


  # Prevent pushing this gem to RubyGems.org. To allow pushes either set the 'allowed_push_host'
  # to allow pushing to a single host or delete this section to allow pushing to any host.
  if s.respond_to?(:metadata)
    s.metadata['allowed_push_host'] = "TODO: Set to 'http://mygemserver.com'"
  else
    raise "RubyGems 2.0 or newer is required to protect against " \
      "public gem pushes."
  end

  s.files         = `git ls-files -z`.split("\x0").reject do |f|
    f.match(%r{^(test|spec|features)/})
  end
  s.bindir        = "exe"
  s.executables   = s.files.grep(%r{^exe/}) { |f| File.basename(f) }
  s.require_paths = ["lib"]

  s.add_development_dependency "bundler", "~> 1.14"
  s.add_development_dependency "rake", "~> 10.0"
  s.add_development_dependency "minitest", "~> 5.0"
end

Gem::PackageTask.new(spec) do |pkg|

end

Rake::ExtensionTask.new('constraint')


Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList['test/**/*_test.rb']
end